'use client';
import {useState} from 'react';
import {useForm} from 'react-hook-form';
import {zodResolver} from '@hookform/resolvers/zod';
import {interviewSchema} from '../../lib/validations';
import {POSITIONS,SOURCES,COMPANY_TYPES} from '../../lib/constants';
import CameraCapture from './CameraCapture';import SkillsInput from './SkillsInput';import GoogleDriveModal from './GoogleDriveModal';
import api from '../../lib/api';import toast from 'react-hot-toast';import {Plus,X,FileText,Upload,Trash2} from 'lucide-react';
const Field=({label,required,children,error})=><div><label className="label">{label}{required?' *':''}</label>{children}{error&&<div className="error">{error.message}</div>}</div>;
function dataUrlToBlob(dataUrl){const [meta,data]=dataUrl.split(',');const bytes=atob(data);const arr=new Uint8Array(bytes.length);for(let i=0;i<bytes.length;i++)arr[i]=bytes.charCodeAt(i);return new Blob([arr],{type:meta.match(/:(.*?);/)[1]})}
export default function InterviewForm(){
 const {register,handleSubmit,formState:{errors},setValue,watch}=useForm({resolver:zodResolver(interviewSchema),defaultValues:{coreTechnicalSkills:[],aiTools:[],previousCompanies:[],appraisalHistory:[],references:[]},mode:'onBlur'});
 const [photo,setPhoto]=useState('');const [skills,setSkills]=useState([]);const [aiTools,setAiTools]=useState([]);const [prev,setPrev]=useState([]);const [apps,setApps]=useState([]);const [refs,setRefs]=useState([]);const [resume,setResume]=useState(null);const [drive,setDrive]=useState(false);const [submitting,setSubmitting]=useState(false);
 const onSubmit=async(data)=>{if(!photo){toast.error('Please capture candidate photo');return}if(!resume){toast.error('Please upload your resume');return}setSubmitting(true);try{const fd=new FormData();fd.append('candidateImage',dataUrlToBlob(photo),'candidate.jpg');fd.append('resume',resume);const payload={...data,coreTechnicalSkills:skills,aiTools,previousCompanies:prev,appraisalHistory:apps,references:refs};fd.append('data',JSON.stringify(payload));await api.post('/interviews',fd,{headers:{'Content-Type':'multipart/form-data'}});window.location.href='/visit/success'}catch(e){toast.error(e?.response?.data?.message||'Unable to submit your application. Please try again.')}finally{setSubmitting(false)}};
 const addPrev=()=>setPrev([...prev,{companyName:'',ctcPerAnnum:'',monthlyTakeHome:'',yearsWorked:''}]);const addApp=()=>setApps([...apps,{year:'',appraisalPercentage:''}]);const addRef=()=>setRefs([...refs,{name:'',phone:'',email:'',currentCompany:''}]);
 return <form onSubmit={handleSubmit(onSubmit)} className="space-y-4">
  <section className="section-card"><h2 className="section-title">Candidate Information</h2><div className="mb-5"><CameraCapture value={photo} onChange={setPhoto}/></div><div className="grid grid-cols-2 gap-3 grid-mobile-1">
   <Field label="Full Name" required error={errors.fullName}><input className="field" placeholder="Enter your full name" {...register('fullName')}/></Field>
   <Field label="Phone Number" required error={errors.phone}><input className="field" inputMode="numeric" maxLength={10} placeholder="10-digit phone number" {...register('phone')}/></Field>
   <Field label="Email ID" required error={errors.email}><input className="field" type="email" placeholder="e.g. user@example.com" {...register('email')}/></Field>
   <Field label="Date of Birth" required error={errors.dateOfBirth}><input className="field" type="date" {...register('dateOfBirth')}/></Field>
  </div></section>
  <section className="section-card"><h2 className="section-title">Professional Details</h2><div className="grid grid-cols-2 gap-3 grid-mobile-1">
   <div className="col-span-2"><Field label="Position Applied For" required error={errors.positionAppliedFor}><select className="field" {...register('positionAppliedFor')}><option value="">Select Position Applied For</option>{POSITIONS.map(x=><option key={x}>{x}</option>)}</select></Field></div>
   <Field label="Select Source" required error={errors.source}><select className="field" {...register('source')}><option value="">Select Source</option>{SOURCES.map(x=><option key={x}>{x}</option>)}</select></Field>
   <Field label="Current Company Name"><input className="field" placeholder="Current Company Name" {...register('currentCompanyName')}/></Field>
   <Field label="Company Type"><select className="field" {...register('companyType')}><option value="">Company Type</option>{COMPANY_TYPES.map(x=><option key={x}>{x}</option>)}</select></Field>
   <Field label="Total Experience"><input className="field" placeholder="e.g. 2.1, 3.5, 7.5" {...register('totalExperience')}/></Field>
   <Field label="Relevant Experience"><input className="field" placeholder="e.g. 1.2, 2.8, 4.3" {...register('relevantExperience')}/></Field>
   <div className="col-span-2"><Field label="Reason for Job Change"><textarea className="field min-h-24" placeholder="Reason for Job Change" {...register('reasonForChange')}/></Field></div>
  </div></section>
  <section className="section-card"><h2 className="section-title">Skills & AI</h2><div className="space-y-4">
   <div><label className="label">Core Technical Skills</label><SkillsInput value={skills} onChange={setSkills} placeholder="Enter technical skills (e.g. Java, Python, React)"/></div>
   <Field label="AI Knowledge / Understanding"><textarea className="field min-h-24" placeholder="Describe your AI knowledge and experience" {...register('aiKnowledge')}/></Field>
   <div><label className="label">AI Skills / Tools Used</label><SkillsInput value={aiTools} onChange={setAiTools} placeholder="Type an AI tool..."/></div>
  </div></section>
  <section className="section-card"><h2 className="section-title">Compensation Details *</h2><div className="grid grid-cols-2 gap-3 grid-mobile-1">
   <Field label="CTC Per Annum (LPA)" required error={errors.ctcPerAnnum}><input className="field" inputMode="decimal" placeholder="CTC Per Annum (LPA)" {...register('ctcPerAnnum')}/></Field>
   <Field label="Monthly Take Home" required error={errors.monthlyTakeHome}><input className="field" inputMode="decimal" placeholder="Monthly Take Home" {...register('monthlyTakeHome')}/></Field>
   <Field label="Expected CTC (LPA)" required error={errors.expectedCtc}><input className="field" inputMode="decimal" placeholder="Expected CTC (LPA)" {...register('expectedCtc')}/></Field>
   <Field label="Notice Period" required error={errors.noticePeriod}><input className="field" placeholder="Notice Period" {...register('noticePeriod')}/></Field>
  </div>
  <button type="button" className="purple-btn mt-4 flex items-center gap-1" onClick={addPrev}><Plus size={15}/> Add Previous Company Compensation Details</button>
  {prev.length>0&&<div className="mt-3 space-y-3">{prev.map((p,i)=><div key={i} className="border border-slate-200 rounded-xl p-3 relative"><button type="button" className="absolute right-3 top-3 text-red-500" onClick={()=>setPrev(prev.filter((_,j)=>j!==i))}><X size={17}/></button><div className="grid grid-cols-2 gap-3 grid-mobile-1 pr-6"><input className="field" placeholder="Previous Company Name" value={p.companyName} onChange={e=>{const a=[...prev];a[i].companyName=e.target.value;setPrev(a)}}/><input className="field" placeholder="CTC Per Annum" value={p.ctcPerAnnum} onChange={e=>{const a=[...prev];a[i].ctcPerAnnum=e.target.value;setPrev(a)}}/><input className="field" placeholder="Monthly Take Home" value={p.monthlyTakeHome} onChange={e=>{const a=[...prev];a[i].monthlyTakeHome=e.target.value;setPrev(a)}}/><input className="field" placeholder="Years Worked" value={p.yearsWorked} onChange={e=>{const a=[...prev];a[i].yearsWorked=e.target.value;setPrev(a)}}/></div></div>)}</div>}
  <button type="button" className="soft-btn mt-4 flex items-center gap-1" onClick={addApp}><Plus size={15}/> Add Appraisal History</button>
  {apps.length>0&&<div className="mt-3 rounded-xl bg-purple-50 p-3"><div className="font-bold text-xs text-purple-900 uppercase mb-2">Appraisal History</div>{apps.map((a,i)=><div key={i} className="grid grid-cols-[1fr_1fr_auto] gap-2 mb-2"><input className="field" placeholder="Year" value={a.year} onChange={e=>{const x=[...apps];x[i].year=e.target.value;setApps(x)}}/><input className="field" placeholder="0-100%" value={a.appraisalPercentage} onChange={e=>{const x=[...apps];x[i].appraisalPercentage=e.target.value;setApps(x)}}/><button type="button" className="text-red-500 px-2" onClick={()=>setApps(apps.filter((_,j)=>j!==i))}><Trash2 size={16}/></button></div>)}<button type="button" className="purple-btn" onClick={addApp}><Plus size={14}/> Add Another Appraisal</button></div>}
  </section>
  <section className="section-card"><h2 className="section-title">Reference Details for Openings at OrangeMantra</h2><button type="button" className="purple-btn flex items-center gap-1" onClick={addRef}><Plus size={15}/> Add Reference Details</button>{refs.map((r,i)=><div key={i} className="mt-3 border border-slate-200 rounded-xl p-3 relative"><button type="button" className="absolute right-3 top-3 text-red-500" onClick={()=>setRefs(refs.filter((_,j)=>j!==i))}><X size={17}/></button><div className="grid grid-cols-2 gap-3 grid-mobile-1 pr-6"><input className="field" placeholder="Name *" value={r.name} onChange={e=>{const x=[...refs];x[i].name=e.target.value;setRefs(x)}}/><input className="field" placeholder="Phone Number *" value={r.phone} onChange={e=>{const x=[...refs];x[i].phone=e.target.value;setRefs(x)}}/><input className="field" placeholder="Email ID *" value={r.email} onChange={e=>{const x=[...refs];x[i].email=e.target.value;setRefs(x)}}/><input className="field" placeholder="Current Company" value={r.currentCompany} onChange={e=>{const x=[...refs];x[i].currentCompany=e.target.value;setRefs(x)}}/></div></div>)}</section>
  <section className="section-card"><h2 className="section-title">Upload CV / Resume</h2><div className="grid grid-cols-2 gap-3 grid-mobile-1"><label className="border border-purple-200 bg-purple-50 rounded-xl p-5 text-center cursor-pointer"><Upload className="mx-auto text-purple-700"/><div className="font-bold text-sm text-purple-800 mt-2">Upload from Device</div><div className="text-[11px] text-purple-500">PDF, DOC or DOCX (Max 10MB)</div><input type="file" accept=".pdf,.doc,.docx,application/pdf,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document" className="hidden" onChange={e=>{const f=e.target.files?.[0];if(!f)return;if(f.size>10*1024*1024){toast.error('File size must be less than 10 MB');e.target.value='';return}const ok=['application/pdf','application/msword','application/vnd.openxmlformats-officedocument.wordprocessingml.document'].includes(f.type)||/\.(pdf|doc|docx)$/i.test(f.name);if(!ok){toast.error('Only PDF, DOC and DOCX files are allowed');e.target.value='';return}setResume(f)}}/></label><button type="button" onClick={()=>setDrive(true)} className="border border-blue-200 bg-blue-50 rounded-xl p-5 text-center"><div className="text-blue-600 text-2xl">↯</div><div className="font-bold text-sm text-blue-800 mt-2">Import from Google Drive</div><div className="text-[11px] text-blue-500">PDF or DOC</div></button></div>{resume&&<div className="mt-3 flex items-center justify-between bg-slate-50 rounded-lg p-3 text-sm"><div className="flex items-center gap-2"><FileText size={18} className="text-purple-700"/><span className="truncate">{resume.name}</span><span className="text-xs text-slate-400">({(resume.size/1024/1024).toFixed(2)} MB)</span></div><button type="button" className="text-red-500" onClick={()=>setResume(null)}><X size={17}/></button></div>}<p className="text-xs text-slate-400 mt-3">Upload your latest CV or Resume in PDF or Word format.</p></section>
  <button disabled={submitting} className="orange-btn w-full text-base">{submitting?'Submitting...':'Submit Application'}</button>
  <GoogleDriveModal open={drive} onClose={()=>setDrive(false)}/>
 </form>
}
